### ISSUE TITLE
website.ymlのdeployジョブで権限不足のエラーが発生しました

### ISSUE THREAD

**Issue by bun913** [textlint/editor-script-template#5]
I am always helped by OSS around textlint. Thank you so much.

## What's ploblem?

In the following section of GitHub Actions, you are deploying to GitHub Pages.

https://github.com/textlint/editor-script-template/blob/532922b7b84ac27cf3f3c82c00fcf54e217c2c58/.github/workflows/website.yml#L30-L34

Currently, if the user is not aware of this, the default GITHUB_TOKEN privilege will be used.

However, it seems that deployments fail because the default permissions only allow read permission on contents.

fyi: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token

## Solution

I create new Access Token that can write `contents` and set into the repository secret.

<img width="810" alt="image" src="https://user-images.githubusercontent.com/73948280/224581088-0f9a1161-4a9a-4359-abeb-ca3246031031.png">

<img width="416" alt="image" src="https://user-images.githubusercontent.com/73948280/224580998-bd7a24a2-1064-4593-9255-83a763f7ce9f.png">

Then, I change workflow file like below.

https://github.com/bun913/textlint-editor-aws-service-name-example/blob/6ef86b086935a160b60e26433934dd625f6dc575/.github/workflows/website.yml#L33

So, I could deploy the GitHub pages.

**Comment by azu** [comment]
[GitHub Actions - Updating the default GITHUB_TOKEN permissions to read-only | GitHub Changelog](https://github.blog/changelog/2023-02-02-github-actions-updating-the-default-github_token-permissions-to-read-only/)

GitHubは最近`permissions`のデフォルト値をread onlyに変更しました。
そのため、`permissions`で明示的に `contents: write` を追加する必要があります。
